Create setup.py
Create this file because of :

```
Run python -m build
ERROR Source /home/runner/work/M1-2022-git-workflow/M1-2022-git-workflow does not appear to be a Python project: no pyproject.toml or setup.py
Error: Process completed with exit code 1.
```